version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deploy/se_project/ # S3에서 가지고온 파일을 저장할 디렉터리
hooks:
  ApplicationStop:
    - location: application_stop.sh
      timeout: 300
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
